name: Keep Render Alive

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      RENDER_BE_URL: ${{ secrets.RENDER_BE_URL }}
    steps:
      - name: Call Render Server
        run: |
          curl -v "$RENDER_BE_URL/health"
